# Generated by Django 5.1.3 on 2024-11-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('socket', models.CharField(max_length=255, verbose_name='Сокет')),
                ('cores', models.IntegerField(verbose_name='Количество ядер')),
                ('releaseYear', models.IntegerField(verbose_name='Год релиза')),
                ('maxThreads', models.IntegerField(verbose_name='Максимальное количество потоков')),
                ('baseClock', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Базовая частота')),
                ('turboClock', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Частота в турбо режиме')),
                ('typeRam', models.CharField(max_length=255, verbose_name='Тип поддерживаемой озу')),
                ('maxRamSize', models.IntegerField(verbose_name='Максимальное поличество озу (Гб)')),
                ('ramFrequency', models.IntegerField(verbose_name='Частота оперативной памяти (МГц)')),
                ('tdp', models.IntegerField(verbose_name='Тепловыделение (Вт)')),
                ('maxTemp', models.IntegerField(verbose_name='Максимальная температура (°C)')),
                ('country', models.CharField(max_length=255, verbose_name='Страна производителя')),
                ('amount', models.IntegerField(verbose_name='Цена ($)')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
            },
        ),
    ]
