# Generated by Django 5.1.3 on 2024-11-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherBroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('series', models.CharField(max_length=255, verbose_name='Серия')),
                ('fromFactor', models.CharField(max_length=255, verbose_name='Форм фактор')),
                ('height', models.IntegerField(verbose_name='Высота (мм)')),
                ('width', models.IntegerField(verbose_name='Ширана (мм)')),
                ('socket', models.CharField(max_length=255, verbose_name='Сокет')),
                ('formFactorOfSupportedMemory', models.CharField(max_length=255, verbose_name='Форм фактор озу')),
                ('ramType', models.CharField(max_length=255, verbose_name='Тип озу')),
                ('ramSlots', models.IntegerField(verbose_name='Количество слотов озу')),
                ('ramFrequency', models.IntegerField(verbose_name='Частота оперативной памяти (МГц)')),
                ('sataConnectors', models.IntegerField(verbose_name='Количество портов Сата')),
                ('usbTypeASlots', models.IntegerField(verbose_name='Количество потров usb type-A')),
                ('country', models.CharField(max_length=255, verbose_name='Страна производителя')),
                ('amount', models.IntegerField(verbose_name='Цена ($)')),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнскаие платы',
            },
        ),
        migrations.CreateModel(
            name='PowerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('formFactor', models.CharField(max_length=255, verbose_name='Форм фактор')),
                ('mainPowerConnector', models.CharField(max_length=255, verbose_name='Основной разъем питания')),
                ('connectorsForProcessor', models.CharField(max_length=255, verbose_name='Разъемы для питания процессора')),
                ('connectorsForVideoCard', models.CharField(max_length=255, verbose_name='Разъемы для питания видеокарты')),
                ('numbersForSata', models.IntegerField(verbose_name='Количество разъемов 15-pin SATA')),
                ('linePower12V', models.IntegerField(verbose_name='Мощность по линии 12 В')),
                ('lineCurrent12V', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Ток по линии +12 В')),
                ('networkVoltage', models.CharField(max_length=255, verbose_name='Диапазон входного напряжения сети')),
                ('country', models.CharField(max_length=255, verbose_name='Страна производителя')),
                ('amount', models.IntegerField(verbose_name='Цена ($)')),
            ],
            options={
                'verbose_name': 'Блок питания',
                'verbose_name_plural': 'Блоки питания',
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('type', models.CharField(max_length=255, verbose_name='Тип озу')),
                ('capacity', models.CharField(max_length=255, verbose_name='Емкость')),
                ('clockSpeed', models.IntegerField(verbose_name='Частота')),
                ('formFactor', models.CharField(max_length=255, verbose_name='Форм фактор')),
                ('rgbBacklight', models.CharField(max_length=255, verbose_name='RGB подцветка')),
                ('country', models.CharField(max_length=255, verbose_name='Страна производителя')),
                ('amount', models.IntegerField(verbose_name='Цена ($)')),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
            },
        ),
    ]
